name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  call-workflow:
    permissions:
      contents: write
      pull-requests: write
    uses: NASA-JPL-Teamtools-Studio/tts_ci_cd/.github/workflows/run_tests_on_pr.yml@main
    with:
      package_name: 'tts_html_utils'